apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: simplepythonapp
build:
  artifacts:
    - image: emanum/k8splayground-simplepythonapp
      docker:
        cacheFrom:
          # Local Docker builder replaces cache references to the artifact image with
          # the tagged image reference, useful for caching from the previous build.
          - emanum/k8splayground-simplepythonapp:latest
  local: {}